<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StellarMinds.Infraestructura\StellarMinds.Infraestructura.csproj" />
    <ProjectReference Include="..\StellarMinds.LogicaAplicacion\StellarMinds.LogicaAplicacion.csproj" />
    <ProjectReference Include="..\StellarMinds.LogicaNegocio\StellarMinds.LogicaNegocio.csproj" />
  </ItemGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<WarningLevel>5</WarningLevel>
	</PropertyGroup>

</Project>
