// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarMinds.Infraestructura.EF;

#nullable disable

namespace StellarMinds.Infraestructura.Migrations
{
    [DbContext(typeof(StellarMindContext))]
    [Migration("20260519220345_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.ObjetosCelestes.ObjetoCeleste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Magnitud")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObjetosCelestes");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Camara", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo");

                    b.Property<int>("Resolucion")
                        .HasColumnType("int");

                    b.Property<int>("TamanioPixel")
                        .HasColumnType("int");

                    b.Property<int>("TipoSensorCamara")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camara");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Montura", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo");

                    b.Property<double>("CargaUtilSoportada")
                        .HasColumnType("float");

                    b.Property<bool>("Computarizada")
                        .HasColumnType("bit");

                    b.Property<int>("TipoMontura")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Montura");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Ocular", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo");

                    b.Property<int>("AnguloVision")
                        .HasColumnType("int");

                    b.Property<double>("Diametro")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Ocular");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Telescopio", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo");

                    b.Property<double>("Apertura")
                        .HasColumnType("float");

                    b.Property<double>("DistanciaFocal")
                        .HasColumnType("float");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("RelacionFocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Telescopio");
                });
#pragma warning restore 612, 618
        }
    }
}
