// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarMinds.Infraestructura.EF;

#nullable disable

namespace StellarMinds.Infraestructura.Migrations
{
    [DbContext(typeof(StellarMindContext))]
    [Migration("20260526003739_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("TipoEquipo").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.NochesObservaciones.NocheObservacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaObservacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObjetoCelesteId")
                        .HasColumnType("int");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjetoCelesteId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("NochesObservaciones");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.ObjetosCelestes.ObjetoCeleste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObjetosCelestes");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Prestamos.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CamaraId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonturaId")
                        .HasColumnType("int");

                    b.Property<int>("OcularId")
                        .HasColumnType("int");

                    b.Property<int>("TelescopioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CamaraId");

                    b.HasIndex("MonturaId");

                    b.HasIndex("OcularId");

                    b.HasIndex("TelescopioId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Camara", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo");

                    b.Property<int>("Resolucion")
                        .HasColumnType("int");

                    b.Property<int>("TamanioPixel")
                        .HasColumnType("int");

                    b.Property<string>("TipoSensorCamara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Camara");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Montura", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo");

                    b.Property<double>("CargaUtilSoportada")
                        .HasColumnType("float");

                    b.Property<bool>("Computarizada")
                        .HasColumnType("bit");

                    b.Property<string>("TipoMontura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Montura");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Ocular", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo");

                    b.Property<int>("AnguloVision")
                        .HasColumnType("int");

                    b.Property<double>("Diametro")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Ocular");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipos.Telescopio", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipos.Equipo");

                    b.Property<double>("Apertura")
                        .HasColumnType("float");

                    b.Property<double>("DistanciaFocal")
                        .HasColumnType("float");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("RelacionFocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Telescopio");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuarios.Administrador", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuarios.Coordinador", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue("Coordinador");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuarios.Socio", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue("Socio");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.NochesObservaciones.NocheObservacion", b =>
                {
                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.ObjetosCelestes.ObjetoCeleste", "ObjetoCeleste")
                        .WithMany()
                        .HasForeignKey("ObjetoCelesteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Prestamos.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjetoCeleste");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.ObjetosCelestes.ObjetoCeleste", b =>
                {
                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOMagnitudAparente", "Magnitud", b1 =>
                        {
                            b1.Property<int>("ObjetoCelesteId")
                                .HasColumnType("int");

                            b1.Property<double>("Valor")
                                .HasColumnType("float")
                                .HasColumnName("Magnitud");

                            b1.HasKey("ObjetoCelesteId");

                            b1.ToTable("ObjetosCelestes");

                            b1.WithOwner()
                                .HasForeignKey("ObjetoCelesteId");
                        });

                    b.Navigation("Magnitud")
                        .IsRequired();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Prestamos.Prestamo", b =>
                {
                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Equipos.Camara", "Camara")
                        .WithMany()
                        .HasForeignKey("CamaraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Equipos.Montura", "Montura")
                        .WithMany()
                        .HasForeignKey("MonturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Equipos.Ocular", "Ocular")
                        .WithMany()
                        .HasForeignKey("OcularId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Equipos.Telescopio", "Telescopio")
                        .WithMany()
                        .HasForeignKey("TelescopioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Camara");

                    b.Navigation("Montura");

                    b.Navigation("Ocular");

                    b.Navigation("Telescopio");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOUsuario.VONombreCompleto", "NombreCompleto", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOUsuario.VOPassword", "VOPassword", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOUsuario.VOTelefono", "Telefono", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.VO.VOUsuario.VOUsername", "Username", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("NombreCompleto")
                        .IsRequired();

                    b.Navigation("Telefono")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();

                    b.Navigation("VOPassword")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
